// GENERATED by the admin panel - do not edit by hand.
// Change this from the "اطلاعات تماس" screen; the next publish rewrites it.
// International format: no +, spaces, or leading zero.
export const WHATSAPP_NUMBER = '989153138150';
export const WHATSAPP_URL = `https://wa.me/${WHATSAPP_NUMBER}`;
