import type { LanguageCode } from '../i18n';

// GENERATED by the admin panel - do not edit by hand.
// The About page's people: the CEO, the team roster and the regional
// representatives. Change these from the "تیم و نمایندگان" screen; the next
// publish rewrites this file.
//
// This used to live inline in src/pages/[lang]/about.astro. The shape is
// unchanged, so the page still does `ceoByLanguage[lang] ?? ceoByLanguage.en`
// exactly as before.

export interface CeoCopy {
  eyebrow: string;
  name: string;
  role: string;
  intro: string;
  quote: string;
}

export interface Person {
  photo: string;
  name: string;
  role: string;
}

export interface PeopleSection {
  kicker: string;
  title: string;
  roster: Person[];
}

export interface RepresentativeEntry {
  photo: string;
  /** Optional backdrop behind the portrait. */
  landmark?: string;
  name: string;
  role: string;
  flag: string;
  country: string;
  /** Falls back to the company number when absent. */
  phone?: string;
}

export interface RepresentativesSection {
  eyebrow: string;
  title: string;
  kicker: string;
  roster: RepresentativeEntry[];
}

export const ceoImage = '/images/CEO.webp';

export const ceoByLanguage: Record<LanguageCode, CeoCopy> = {
  en: {
    eyebrow: 'Leadership',
    name: 'Mr. Majid Rokhsati',
    role: 'Chief Executive Officer',
    intro: 'Our leadership is focused on building reliable long-term trading relationships across Central Asia, Russia, and neighboring markets.',
    quote: 'We believe sustainable trade is built on trust, clear commitments, and reliable execution from sourcing to delivery.',
  },
  fa: {
    eyebrow: 'مدیریت',
    name: 'آقای مجید رخصتی',
    role: 'مدیرعامل',
    intro: 'تمرکز مدیریت شرکت بر ایجاد روابط تجاری بلندمدت و قابل‌اعتماد در آسیای مرکزی، روسیه و بازارهای منطقه است.',
    quote: 'ما معتقدیم تجارت پایدار بر اعتماد، تعهد روشن و اجرای قابل‌اتکا از تأمین تا تحویل شکل می‌گیرد.',
  },
  ar: {
    eyebrow: 'الإدارة',
    name: 'السيد مجيد رخصتي',
    role: 'الرئيس التنفيذي',
    intro: 'تركز إدارة الشركة على بناء علاقات تجارية طويلة الأجل وموثوقة في آسيا الوسطى وروسيا والأسواق الإقليمية.',
    quote: 'نؤمن أن التجارة المستدامة تقوم على الثقة والالتزام الواضح والتنفيذ الموثوق من التوريد حتى التسليم.',
  },
  ru: {
    eyebrow: 'Руководство',
    name: 'Г-н Маджид Рохсати',
    role: 'Генеральный директор',
    intro: 'Руководство компании сосредоточено на развитии надежных долгосрочных торговых отношений в Центральной Азии, России и соседних рынках.',
    quote: 'Мы считаем, что устойчивый бизнес строится на доверии, четких обязательствах и надежном исполнении от закупки до поставки.',
  },
};

export const peopleByLanguage: Record<LanguageCode, PeopleSection> = {
  en: {
    kicker: 'The people leading Zardasht Mahd Binaloud Trading, from sourcing to delivery.',
    title: 'Our people',
    roster: [
      { photo: '/images/CEO.webp', name: 'Mr. Majid Rokhsati', role: 'Chief Executive Officer' },
      { photo: '/images/CEO.webp', name: 'Commercial Manager', role: 'Sourcing, supplier relationships and trade terms' },
      { photo: '/images/CEO.webp', name: 'Logistics & Operations Manager', role: 'Freight, customs clearance and delivery' },
    ],
  },
  fa: {
    kicker: 'افرادی که بازرگانی زردشت مهد بینالود را از تأمین تا تحویل هدایت می‌کنند.',
    title: 'تیم ما',
    roster: [
      { photo: '/images/CEO.webp', name: 'آقای مجید رخصتی', role: 'مدیرعامل' },
      { photo: '/images/CEO.webp', name: 'مدیر بازرگانی', role: 'تأمین، ارتباط با تأمین‌کنندگان و شرایط معامله' },
      { photo: '/images/CEO.webp', name: 'مدیر لجستیک و عملیات', role: 'حمل، ترخیص گمرکی و تحویل' },
    ],
  },
  ar: {
    kicker: 'الأشخاص الذين يقودون شركة زردشت مهد بينالود التجارية من التوريد حتى التسليم.',
    title: 'فريقنا',
    roster: [
      { photo: '/images/CEO.webp', name: 'السيد مجيد رخصتي', role: 'الرئيس التنفيذي' },
      { photo: '/images/CEO.webp', name: 'مدير تجاري', role: 'التوريد وعلاقات الموردين وشروط الصفقة' },
      { photo: '/images/CEO.webp', name: 'مدير اللوجستيات والعمليات', role: 'الشحن والتخليص الجمركي والتسليم' },
    ],
  },
  ru: {
    kicker: 'Люди, которые ведут Zardasht Mahd Binaloud Trading от закупки до доставки.',
    title: 'Наша команда',
    roster: [
      { photo: '/images/CEO.webp', name: 'Г-н Маджид Рохсати', role: 'Генеральный директор' },
      { photo: '/images/CEO.webp', name: 'Коммерческий директор', role: 'Закупки, отношения с поставщиками и условия сделок' },
      { photo: '/images/CEO.webp', name: 'Директор по логистике и операциям', role: 'Перевозка, таможенное оформление и доставка' },
    ],
  },
};

export const representativesByLanguage: Record<LanguageCode, RepresentativesSection> = {
  en: {
    eyebrow: 'Our network',
    title: 'Our representatives in the region',
    kicker: 'A local contact in each of our key markets, not a handoff to a stranger.',
    roster: [
      { photo: '/images/rep-korosh.webp', name: 'Kourosh Rokhsat', role: 'Representative', flag: '/images/flag-uz.webp', country: 'Uzbekistan' },
      { photo: '/images/rep-korosh.webp', name: 'Kourosh Rokhsat', role: 'Representative', flag: '/images/flag-kz.webp', country: 'Kazakhstan' },
      { photo: '/images/rep-korosh.webp', landmark: '/images/landmark-russia.webp', name: 'Kourosh Rokhsat', role: 'Representative', flag: '/images/flag-ru.webp', country: 'Russia' },
    ],
  },
  fa: {
    eyebrow: 'شبکه ما',
    title: 'نمایندگان ما در منطقه',
    kicker: 'در هر بازار کلیدی، یک تماس محلی و مستقیم داریم؛ نه واگذاری به یک غریبه.',
    roster: [
      { photo: '/images/rep-korosh.webp', name: 'کوروش رخصت', role: 'نماینده', flag: '/images/flag-uz.webp', country: 'ازبکستان' },
      { photo: '/images/rep-korosh.webp', name: 'کوروش رخصت', role: 'نماینده', flag: '/images/flag-kz.webp', country: 'قزاقستان' },
      { photo: '/images/rep-korosh.webp', landmark: '/images/landmark-russia.webp', name: 'کوروش رخصت', role: 'نماینده', flag: '/images/flag-ru.webp', country: 'روسیه' },
    ],
  },
  ar: {
    eyebrow: 'شبكتنا',
    title: 'ممثلونا في المنطقة',
    kicker: 'جهة اتصال محلية في كل سوق رئيسي، لا تسليم إلى شخص غريب.',
    roster: [
      { photo: '/images/rep-korosh.webp', name: 'كوروش رخصت', role: 'ممثل', flag: '/images/flag-uz.webp', country: 'أوزبكستان' },
      { photo: '/images/rep-korosh.webp', name: 'كوروش رخصت', role: 'ممثل', flag: '/images/flag-kz.webp', country: 'كازاخستان' },
      { photo: '/images/rep-korosh.webp', landmark: '/images/landmark-russia.webp', name: 'كوروش رخصت', role: 'ممثل', flag: '/images/flag-ru.webp', country: 'روسيا' },
    ],
  },
  ru: {
    eyebrow: 'Наша сеть',
    title: 'Наши представители в регионе',
    kicker: 'Локальный контакт на каждом ключевом рынке — а не передача незнакомцу.',
    roster: [
      { photo: '/images/rep-korosh.webp', name: 'Куруш Рохсат', role: 'Представитель', flag: '/images/flag-uz.webp', country: 'Узбекистан' },
      { photo: '/images/rep-korosh.webp', name: 'Куруш Рохсат', role: 'Представитель', flag: '/images/flag-kz.webp', country: 'Казахстан' },
      { photo: '/images/rep-korosh.webp', landmark: '/images/landmark-russia.webp', name: 'Куруш Рохсат', role: 'Представитель', flag: '/images/flag-ru.webp', country: 'Россия' },
    ],
  },
};
